Bug 1997025 - Replace u8"" string literals in TestUriTemplate test. r=necko-reviewers,sunil
u8"" strings have type const char[] in C++17, but type const char8_t[] in C++20. Since most Firefox code is written assuming char or char16_t strings, char8_t strings cause type mismatches that would require additional overloads or string conversions.

Because Firefox .cpp files are compiled as UTF-8, "" string literals are already UTF-8 encoded and the explicit u8 prefix is unnecessary.

```
netwerk/test/gtest/TestUriTemplate.cpp:79:49: error: no matching literal operator for call to 'operator""_ns' with arguments of types 'const char8_t *' and 'unsigned long', and no matching literal operator template

79 | ASSERT_EQ(builder->Set("name"_ns, u8"München"_ns), NS_OK);
```

Differential Revision: https://phabricator.services.mozilla.com/D270452